"""translations = {
    "Tiếng Việt": {
        "mysql_title": "Đăng nhập MySQL",
        "mysql_label": "Đăng nhập MySQL",
        "db_host": "Máy chủ CSDL:",
        "db_username": "Tên đăng nhập CSDL:",
        "db_password": "Mật khẩu CSDL:",
        "language": "Ngôn ngữ:",
        "login": "Đăng nhập",
        "exit": "Thoát",
        "remember": "Nhớ tôi",
        "user_title": "Đăng nhập người dùng",
        "username": "Tên đăng nhập:",
        "password": "Mật khẩu:",
        "back": "Quay lại",
        "control_title": "Bảng điều khiển",
        "welcome": "Chào mừng",
        "manage": "Quản lý học sinh",
        "attendance": "Điểm danh",
        "export": "Xuất danh sách",
        "edit": "Chỉnh sửa học sinh",
        "quit": "Thoát",
        "logout": "Đăng xuất",
        "no_data": "Không Có Dữ Liệu :(",
        "toggle_dark": "Chuyển sang Dark",
        "toggle_light": "Chuyển sang Light",
        "col_index": "Số Thứ Tự",
        "col_name": "Tên Học Sinh",
        "col_attendance": "Điểm Danh",
        "search": "Tìm kiếm",
        "reason": "Lý do",
        "add_student": "Thêm học sinh",
        "delete_student": "Xoá học sinh",
        "edit_student": "Chỉnh sửa học sinh",
        "set_cutoff": "Cài đặt hạn chót",
        "add_user": "Thêm tài khoản",
        "delete_user": "Xoá tài khoản",
        "edit_user": "Chỉnh sửa tài khoản",
        "user_accounts_tab": "Quản lý tài khoản",
        "students_tab": "Quản lý học sinh",
        "choose_folder": "Chọn thư mục chứa ảnh",
        "invalid_filename_format": "Tên file không hợp lệ. Định dạng yêu cầu: Họ_Tên_Lớp",
        "batch_add_success": "Đã thêm {count} học sinh từ thư mục.",
        "batch_add": "Thêm hàng loạt",
        "add_student_from_image": "Thêm học sinh từ ảnh",
        "browse_image": "Chọn ảnh",
        "camera_header": "Cấu hình Camera",
        "camera_type_label": "Loại kết nối camera:",
        "camera_url_label": "Địa chỉ URL:",
        "simple_mode": "Chế độ đơn giản",
        "connection_mode": "Chế độ kết nối:",
        "camera_username_label": "Tên tài khoản:",
        "camera_password_label": "Mật khẩu:",
        "camera_ip_label": "IP của camera:",
        "camera_port_label": "Cổng:",
        "generate_link": "Tạo link",
        "gmt": "GMT:",
        "cutoff_time": "Hạn chót (HH:MM):",
        "submit": "Gửi",
        "invalid_time_format": "Định dạng giờ không hợp lệ. Vui lòng nhập HH:MM.",
        "cutoff_set_success": "Cài đặt hạn chót thành công.",
    },
    "English": {
        "mysql_title": "MySQL Login",
        "mysql_label": "MySQL Login",
        "db_host": "Database Host:",
        "db_username": "Database Username:",
        "db_password": "Database Password:",
        "language": "Language:",
        "login": "Login",
        "exit": "Exit",
        "remember": "Remember me",
        "user_title": "User Login",
        "username": "Username:",
        "password": "Password:",
        "back": "Back",
        "control_title": "Control Panel",
        "welcome": "Welcome",
        "manage": "Manage Students",
        "attendance": "Attendance",
        "export": "Export List",
        "edit": "Edit Students",
        "quit": "Quit",
        "logout": "Log Out",
        "no_data": "No Data :(",
        "toggle_dark": "Switch to Dark",
        "toggle_light": "Switch to Light",
        "col_index": "STT",
        "col_name": "Student Name",
        "col_attendance": "Attendance",
        "search": "Search",
        "reason": "Reason",
        "add_student": "Add Student",
        "delete_student": "Delete Student",
        "edit_student": "Edit Student",
        "set_cutoff": "Set Cutoff Time",
        "add_user": "Add User",
        "delete_user": "Delete User",
        "edit_user": "Edit User",
        "user_accounts_tab": "User Account Management",
        "students_tab": "Student Management",
        "choose_folder": "Select folder containing images",
        "invalid_filename_format": "Invalid filename format. Required format: Name_Class",
        "batch_add_success": "Added {count} students from folder.",
        "batch_add": "Batch Add",
        "add_student_from_image": "Add Student from Images",
        "browse_image": "Browse Image",
        "camera_header": "Camera Configuration",
        "camera_type_label": "Camera Type:",
        "camera_url_label": "Camera URL:",
        "simple_mode": "Simple Mode",
        "connection_mode": "Connection Type:",
        "camera_username_label": "Username:",
        "camera_password_label": "Password:",
        "camera_ip_label": "Camera IP:",
        "camera_port_label": "Port:",
        "generate_link": "Generate Link",
        "gmt": "GMT:",
        "cutoff_time": "Cutoff Time (HH:MM):",
        "submit": "Submit",
        "invalid_time_format": "Invalid time format. Please enter HH:MM.",
        "cutoff_set_success": "Cutoff time set successfully.",
    }
}"""
import os
import requests
import urllib3
from pathlib import Path
from urllib.parse import urlparse

# Tắt cảnh báo InsecureRequestWarning (do verify=False)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Danh sách đầy đủ các URL ảnh mà bạn cung cấp
urls = [
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/1-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/2-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/3-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/4-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/5-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/6-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/7-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/8-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/9-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/10-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/11-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/12-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/13-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/14-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/15-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/16-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/17-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/18-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/19-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/20-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/21-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/22-1.thumb128.webp",
    "https://imgcdn.sstick.com/k5Munc6RCQetp2SV8Qtp/23-1.thumb128.webp",
    "https://imgcdn.sstick.com/hXy1R6r5YFrF4L5K1cjMI/cover-1.thumb128.webp",
    "https://imgcdn.sstick.com/hXy1R6r5YFrF4L5K1cjMI/1-1.thumb128.webp",
    "https://imgcdn.sstick.com/hXy1R6r5YFrF4L5K1cjMI/2-1.thumb128.webp",
    "https://imgcdn.sstick.com/hXy1R6r5YFrF4L5K1cjMI/3-1.thumb128.webp",
    "https://imgcdn.sstick.com/hXy1R6r5YFrF4L5K1cjMI/4-1.thumb128.webp",
    "https://imgcdn.sstick.com/Js7iYcz0SKvMCcC9B1uhQv/1-1.thumb128.png",
    "https://imgcdn.sstick.com/Jsi7EcKxyhW0cC9B1uhQ/2-1.thumb128.png",
    "https://imgcdn.sstick.com/Jsi7EcKxyhW0cC9B1uhQ/3-1.thumb128.png",
    "https://imgcdn.sstick.com/Jsi7EcKxyhW0cC9B1uhQ/4-1.thumb128.png",
    "https://imgcdn.sstick.com/2r0Xw88Jq8qPd95n1FfIa/cover-1.thumb128.png",
    "https://imgcdn.sstick.com/2r0Xw88Jq8qPd95n1FfIa/1-1.thumb128.png",
    "https://imgcdn.sstick.com/2r0Xw88Jq8qPd95n1FfIa/2-1.thumb128.png",
    "https://imgcdn.sstick.com/2r0Xw88Jq8qPd95n1FfIa/3-1.thumb128.png",
    "https://imgcdn.sstick.com/2r0Xw88Jq8qPd95n1FfIa/4-1.thumb128.png",
    "https://imgcdn.sstick.com/zfTyucjF8kjJDZx7iMU8U/cover-1.thumb128.png",
    "https://imgcdn.sstick.com/zfTyucjF8kjJDZx7iMU8U/1-1.thumb128.png",
    "https://imgcdn.sstick.com/zfTyucjF8kjJDZx7iMU8U/2-1.thumb128.png",
    "https://imgcdn.sstick.com/zfTyucjF8kjJDZx7iMU8U/3-1.thumb128.png",
    "https://imgcdn.sstick.com/zfTyucjF8kjJDZx7iMU8U/4-1.thumb128.png",
    "https://imgcdn.sstick.com/snIF4V6Xemd3C7AQ1Hi/cover-1.thumb128.png",
    "https://imgcdn.sstick.com/snIF4V6Xemd3C7AQ1Hi/1-1.thumb128.png",
    "https://imgcdn.sstick.com/snIF4V6Xemd3C7AQ1Hi/2-1.thumb128.png",
    "https://imgcdn.sstick.com/snIF4V6Xemd3C7AQ1Hi/3-1.thumb128.png",
    "https://imgcdn.sstick.com/snIF4V6Xemd3C7AQ1Hi/4-1.thumb128.png",
    "https://imgcdn.sstick.com/jiWmeTDW9jeg7X9GkFRiZ/cover-1.thumb128.png",
    "https://imgcdn.sstick.com/jiWmeTDW9jeg7X9GkFRiZ/1-1.thumb128.png",
    "https://imgcdn.sstick.com/jiWmeTDW9jeg7X9GkFRiZ/2-1.thumb128.png",
    "https://imgcdn.sstick.com/jiWmeTDW9jeg7X9GkFRiZ/3-1.thumb128.png",
    "https://imgcdn.sstick.com/jiWmeTDW9jeg7X9GkFRiZ/4-1.thumb128.png",
    "https://imgcdn.sstick.com/cGaENMcsPmRNvsN6b9F2/cover-1.thumb128.png",
    "https://imgcdn.sstick.com/cGaENMcsPmRNvsN6b9F2/1-1.thumb128.png",
    "https://imgcdn.sstick.com/cGaENMcsPmRNvsN6b9F2/2-1.thumb128.png",
    "https://imgcdn.sstick.com/cGaENMcsPmRNvsN6b9F2/3-1.thumb128.png",
    "https://imgcdn.sstick.com/cGaENMcsPmRNvsN6b9F2/4-1.thumb128.png",
    "https://imgcdn.sstick.com/kbhsfX2BPBy1l/cover-1.thumb128.webp",
    "https://imgcdn.sstick.com/kbhsfX2BPBy1l/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/gQY5jUHQ1hkfXB2PBy11/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/gQY5jUHQ1hkfXB2PBy11/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/gQY5jUHQ1hkfXB2PBy11/4-1.thumb128.webp",
    "https://imgcdn.sipstick.com/xFUWe5M01Alhez1DgmXQ/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/xFUMeSMOiAlhez1DgmX0/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/xFUWe5MOiAlhez1DgmXQ/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/xFUWe5M01Alhez1DgmXQ/3-1.thumb128.png",
    "https://imgcdn.sigstick.com/xFUWe5M0iAlhez1DgmXQ/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/az9LhNcMVaUbrN1OLLId/cover-1.thumb128.webp",
    "https://imgcdn.sigstick.com/az9LhNcMVallbrN1OLLId/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/az9LhNcMVaUbrN1OLLId/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/az9LhNcMVaUbrNIOLLId/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/az9LhNcMVallbrK1OLLId/4-1.thumb128.webp",
    "https://imgcdn.sigstick.com/ODY@kUYbu@fBeVvGiXs1/cover.thumb128.png",
    "https://imgcdn.sigstick.com/ODY@kl/Ybu@fBeVvGjXs1/1.thumb128.png",
    "https://imgcdn.sigstick.com/ODY@kUYbu@fBeVvG1Xs1/2.thumb128.png",
    "https://imgcdn.sigstick.com/OQY0kUYbu@fBeVvGiXs1/3.thumb128.png",
    "https://imgcdn.sigstick.com/ODY@kJYbu@fBeVvG1Xs1/4.thumb128.png",
    "https://imgcdn.sigstick.com/dpZgBZM9wQn0A4eBBzP8/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/dp7gB7M9wQn0A4eBBzP8/2-1.thumb128.png",
    "https://imgcdn.sipstick.com/dpZpB7M9w000A4eBBzP8/2-2.thumb128.png",
    "https://imgcdn.sigstick.com/dpZpBZM9wQn0A4B0zP8/3-5.thumb128.png",
    "https://imgcdn.sigstick.com/dpZpBZM9w0n0A4eB0zP8/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/0vkQ@alifvxbeu1tC80mu/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/@vkQ@alifvxbeultC80mu/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/@vkQ@allfvxbeu1tC80mu/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/evk00aHfvxbeu1tC8@mu/3-1.thumb128.png",
    "https://imgcdn.sigstick.com/@vk00aHfvxbeu1tC80mu/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/cn6QXPD665M6MR1AUb11/cover.thumb128.png",
    "https://imgcdn.sigstick.com/cn6QXPD665M6MR JAUbil / 1.thumb128.png",
    "https://imgcdn.sigstick.com/cn6QXPD665M6MR1AUbj1/2.thumb128.png",
    "https://imgcdn.sigstick.com/cn6QXPD66sM6MRjAUbj1/3.thumb128.png",
    "https://imgcdn.sigstick.com/cn6QXPD66sM6MRjAUbj1/4.thumb128.png",
    "https://imgcdn.sigstick.com/Y6HmEblim68pXh16K8P1/cover.thumb128.png",
    "https://imgcdn.sinstick.com/Y6HwFbL1m68pXh16K8P1/1.thumb128.png",
    "https://imgcdn.sigstick.com/Y6HmEblim68pXhi6K8P1/2.thumb128.png",
    "https://imgcdn.sipstick.com/Y6HmEbt1m68pXhi6K8P1/3,thumb128.png",
    "https://imgcdn.sigstick.com/Y6HmEbLim58pXhi6K8P1/4.thumb128.png",
    "https://imgcdn.sigstick.com/3XFIJJ3@qpyVsQHAeuBr/cover-1.thumb128.webp",
    "https://imgcdn.sigstick.com/3XF11130qpyVsQHAeuBr/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/3XF13330qpyVsQHAeuBr/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/3XF13330qpyVsQHAeuBr/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/3XF1333@qpyVsQHAeuBr/4-1.thumb128.webp",
    "https://imgcdn.sigstick.com/mauC66gbVTWPk1c6I150s/cover.thumb128.png",
    "https://imgcdn.sigstick.com/mguC66gbV1WPkIc6150s/1.thumb128.png",
    "https://imgcdn.sigstick.com/mquC66qbVIWPkIc6150s/2.thumb128.png",
    "https://imgcdn.sigstick.com/mquC66qbVIWPkIc6I50s/3.thumb128.png",
    "https://imgcdn.sigstick.com/mquC66qbVIWPkIc6ISOs/4.thumb128.png",
    "https://imgcdn.sigstick.com/463xcoThz01tPg0xD8W2/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/4GJxcoThz0l1Pg0xD8W2/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/4G)xcoThzOjtPg0xD8W2/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/46JxcoThzQjtPgQxDBW2/3-1.thumb128.png",
    "https://imgcdn.sigstick.com/46JxcoThzQjtPgQxDBW2/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/iilmLUmkma.JoPEf1R19T/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/i1HmLBakma3oPEF1R19T/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/i1HmLBmkmaJoPEf1R19T/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/fihalBakmaJoPEFIR191/3-1.thumb128.png",
    "https://imgcdn.siestick.com/iitmlBmkma.JoPEf18191/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/W18YzSDorzy7BLkuk@1n/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/W1BYzSDorzv7BLkuK01n/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/W1BYzSDorzv7BLkuK01n/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/W18YzSDorzv7BLkuK01n/3-1.thumb128.png",
    "https://imgcdn.sigstick.com/W18YzSDorzv7BLkuK01n/4-1.thumb128.png",
    "https://imgcdn.sigstick.com/kS1EMBnQ4LoerStal5wv/cover-1.thumb128.webp",
    "https://imgcdn.sigstick.com/kS1EMBnQ4LoerStal5wv/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/kS1EMBnQ4LoerStal5wv/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/kS1EMBnQ4LoerStal5wv/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/kS1EMBnQ4LoerStal5wv/4-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1Dya2eQtWg@TeUtPi207/cover-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1Dya2eQtWg@TeUtPi207/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1Dya2eQtWg@TeUtPi207/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1Dya2eQtWg@TeUtPi207/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1Dya2eQtWg@TeUtPi207/4-1.thumb128.webp",
    "https://imgcdn.sigstick.com/Cw5sNkhgPIVe6nPmg0d6/cover-1.thumb128.webp",
    "https://imgcdn.sigstick.com/Cw5sNkhgPIVe6nPmg0d6/1-1.thumb128.webp",
    "https://imgcdn.sigstick.com/Cw5sNkhgPIVe6nPmg0d6/2-1.thumb128.webp",
    "https://imgcdn.sigstick.com/Cw5sNkhgPIVe6nPmg0d6/3-1.thumb128.webp",
    "https://imgcdn.sigstick.com/Cw5sNkhgPIVe6nPmg0d6/4-1.thumb128.webp",
    "https://imgcdn.sigstick.com/1g12dUmv@XQGHScRRLq0/cover-1.thumb128.png",
    "https://imgcdn.sigstick.com/1g12dUmv@XQGHScRRLq0/1-1.thumb128.png",
    "https://imgcdn.sigstick.com/1g12dUmv@XQGHScRRLq0/2-1.thumb128.png",
    "https://imgcdn.sigstick.com/1g12dUmv@XQGHScRRLq0/3-1.thumb128.png",
    "https://imgcdn.sigstick.com/1g12dUmv@XQGHScRRLq0/4-1.thumb128.png"
]

# Tạo thư mục Downloads/GIF trong thư mục người dùng (home directory)
downloads_path = Path.home() / "Downloads" / "GIF"
downloads_path.mkdir(parents=True, exist_ok=True)


def download_image(url):
    try:
        # Lấy tên file từ URL
        file_name = os.path.basename(urlparse(url).path)
        save_path = downloads_path / file_name

        # Gửi request với verify=False để bỏ qua xác thực SSL
        response = requests.get(url, timeout=15, verify=False)
        response.raise_for_status()  # Phát sinh exception nếu mã không phải 200

        with open(save_path, 'wb') as f:
            f.write(response.content)

        print(f"✅ Đã tải: {file_name}")
    except Exception as e:
        print(f"❌ Lỗi khi tải {url}: {e}")


# Duyệt và tải từng ảnh từ danh sách URL
for url in urls:
    download_image(url)
